### ISSUE TITLE
Quickstart sample should use full package name in import

### ISSUE THREAD

**Issue by tswast** [googleapis/nodejs-bigquery-data-transfer#4]
Right now the sample imports `../src`. This is not how users would use the package. The sample should import the released package, as is done for BigQuery. https://github.com/googleapis/nodejs-bigquery/blob/master/samples/quickstart.js#L20

**Comment by alexander-fenster** [comment]
That's true, and the reason here is that we don't have any good samples for this package, other than the auto-generated stub (it's in fact adapted from the smoke test). I can fix this particular sample to look the same as in other libraries (with separate `package.json` depending on the main package), but we should have better manually written samples for this library (the lack of samples is the main reason why it's published as alpha).

**Comment by JustinBeckwith** [comment]
This looks to be fixed :)
